services:
  # PostgreSQL Services
  db:
    image: postgres:13
    restart: always
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: RFS_DB
    ports:
      - "5432:5432"
    volumes:
      - ./Postgres/postgres_data:/var/lib/postgresql/data

  # API Services
  api:
    build: ./RestApiNest
    container_name: nest_api
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_NAME: RFS_DB
    expose:
      - 3000
    depends_on:
      - db
    tty: true  

  # Nginx Services
  nginx:
    build: ./nginx
    container_name: nginx_proxy
    ports:
      - "80:80"
    depends_on:
      - api

volumes:
  postgres_data:
