service: recommendation-feedback

provider:
  name: aws
  runtime: nodejs16.x
  region: us-east-1
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: "1"
    S3_BUCKET: ${self:service}-${self:provider.stage}-files
    DYNAMODB_TABLE: ${self:service}-${self:provider.stage}-feedback
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:PutObject"
        - "s3:GetObject"
        - "s3:DeleteObject"
      Resource: "arn:aws:s3:::${self:provider.environment.S3_BUCKET}/*"
    - Effect: "Allow"
      Action:
        - "dynamodb:PutItem"
        - "dynamodb:Scan"
        - "dynamodb:Query"
        - "dynamodb:GetItem"
        - "dynamodb:UpdateItem"
      Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"
    - Effect: "Allow"
      Action:
        - "sqs:SendMessage"
        - "sqs:ReceiveMessage"
        - "sqs:DeleteMessage"
      Resource: "arn:aws:sqs:${self:provider.region}:*:QueueName"

functions:
  createFeedback:
    handler: src/feedback/createFeedback.handler
    events:
      - http:
          path: feedback
          method: post

  listFeedback:
    handler: src/feedback/listFeedback.handler
    events:
      - http:
          path: feedback
          method: get

resources:
  Resources:
    FeedbackTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
    S3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:provider.environment.S3_BUCKET}
    